/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 Nightly Build 1020
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PWM.h>
#include <Clock.h>
#include <ADC.h>
#include <Pot_aliases.h>
#include <Pot.h>
#include <PWM_out_aliases.h>
#include <PWM_out.h>
#include <LCD.h>
#include <ADC_theACLK.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_AMux.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
