# THIS FILE IS AUTOMATICALLY GENERATED
# Project: Z:\Documents\Github Clones\PSoC.Playground\PROJECTS\Lab1_Led\Lab1_Led.cydsn\Lab1_Led.cyprj
# Date: Tue, 30 Dec 2014 06:05:35 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for Z:\Documents\Github Clones\PSoC.Playground\PROJECTS\Lab1_Led\Lab1_Led.cydsn\TopDesign\TopDesign.cysch
# Project: Z:\Documents\Github Clones\PSoC.Playground\PROJECTS\Lab1_Led\Lab1_Led.cydsn\Lab1_Led.cyprj
# Date: Tue, 30 Dec 2014 06:05:29 GMT
